### ISSUE TITLE
Add option for detection of stashes and refs, etc.  [feature request]

### ISSUE THREAD

**Issue by tbrowder** [lizmat/Git-Status#3]

**Comment by lizmat** [comment]
Not sure what you mean?

Could you elaborate on `git status` parameters to get that information?

**Comment by tbrowder** [comment]
I don't understand Git refs enough, but when using my new git checker and investigating an old repo that showed dirty with uncommitted changes, I stashed them and reran the checker and it showed clean.

Then I thought about suggesting some enhancements to your module such as:

+ showing brances
+ refs and stashes

I don't know if that's possible given your concept of the scope of your module, but it would be handy to know if (1) there are stashes and (2) all branch names (current and other).

If not of interest to or in scope for you, I'll do it in my module, OR I can work on a PR for yours.

**Comment by tbrowder** [comment]
Okay, I think I'm awake now. I can study the 'git help status' more and suggest specifics.

**Comment by tbrowder** [comment]
So maybe there should be separate modules, say, Git::Branch and Git::Stash to keep in scope.

**Comment by lizmat** [comment]
I guess a `Git::Branch` module would make sense   :-)

**Comment by tbrowder** [comment]
So, I think copying this module's design and modifying it for the desired Git command would be fairly straight forward. I'll put that on my TODO list if you aren't interested.

**Comment by lizmat** [comment]
I'm interested, but currently focused on RakuAST and pod :-)

**Comment by tbrowder** [comment]
Oh, yes, please keep that focus!
