### ISSUE TITLE
Provide a binary to report status of a git directory

### ISSUE THREAD

**Issue by tbrowder** [lizmat/Git-Status#5]
Something like:

    gitstatus mydir # OUTPUT: RMD

**Comment by tbrowder** [comment]
Tried to cancel but too late.

**Comment by lizmat** [comment]
What would that bring more than `git status`?

**Comment by tbrowder** [comment]
Probably not much except a single string the user could match against. Using it now I get a list of codes, but I may not be using it correctly. That's why I tried to cancel to play with it more and try a PR.

**Comment by tbrowder** [comment]
Closed as unnecessary after the latest release.
